[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "harpoon"
authors = [{name = "Dominic Holt", email = "dom@harpooncorp.io"}]
dynamic = ["version", "description"]
